---
description: 'This chapter demonstrates how to install numerous desktop environments, including web browsers, productivity software, document viewers, and financial software'
next: books/handbook/multimedia
part: '파트 II. 일반적인 작업'
path: /books/handbook/
prev: books/handbook/partii
showBookMenu: 'true'
tags: ["desktop", "KDE Plasma", "GNOME", "XFCE", "MATE", "Cinnamon", "LXQT", "browsers", "Firefox", "Chromium", "Iridium", "Falkon", "Konqueror", "Epiphany", "qutebrowser", "Dillo", "Links", "w3m", "Development tools", "Visual Studio Code", "Qt Creator", "Kdevelop", "Eclipse IDE", "Vim", "Neovim", "GNU Emacs", "Productivity", "LibreOffice", "Calligra", "AbiWord", "Viewers", "Okular", "Evince", "ePDFView", "Xpdf", "Finance", "KMyMoney", "GnuCash"]
title: 'Chapter 7. Desktop Environments'
weight: 10
---

[[desktop]]
= Desktop Environments
:doctype: book
:toc: macro
:toclevels: 1
:icons: font
:sectnums:
:sectnumlevels: 6
:sectnumoffset: 7
:partnums:
:source-highlighter: rouge
:experimental:
:images-path: books/handbook/desktop/

ifdef::env-beastie[]
ifdef::backend-html5[]
:imagesdir: ../../../../images/{images-path}
endif::[]
ifndef::book[]
include::shared/authors.adoc[]
include::shared/mirrors.adoc[]
include::shared/releases.adoc[]
include::shared/attributes/attributes-{{% lang %}}.adoc[]
include::shared/{{% lang %}}/teams.adoc[]
include::shared/{{% lang %}}/mailing-lists.adoc[]
include::shared/{{% lang %}}/urls.adoc[]
toc::[]
endif::[]
ifdef::backend-pdf,backend-epub3[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]
endif::[]

ifndef::env-beastie[]
toc::[]
include::../../../../../shared/asciidoctor.adoc[]
endif::[]

[[desktop-synopsis]]
== 요약

While FreeBSD is popular as a server for its performance and stability, it is also well suited for day-to-day use as a desktop. With over {numports} applications available in the FreeBSD ports tree, it is straightforward to build a customized desktop that can run a wide variety of desktop applications. This chapter demonstrates how to install popular desktop environments as well as desktop applications such as web browsers, productivity software, document viewers, and financial software.

Prerequisites:

* Readers of this chapter should already understand how to install either the crossref:x11[x11,X Window System] or crossref:wayland[wayland,Wayland] on FreeBSD.
* Readers are instructed throughout this chapter to install official packages. Refer to the section on crossref:ports[ports-using,using the ports collection] to build customized packages from ports.

[[desktop-environments]]
== Desktop Environments

This section describes how to install and configure some popular desktop environments on a FreeBSD system. A desktop environment can range from a simple window manager to a complete suite of desktop applications.

.Supported desktop environments
[options="header", cols="1,1,1"]
|===
| Name | License | Package

| KDE Plasma
| GPL 2.0 or later
| x11/kde5

| GNOME
| GPL 2.0 or later
| x11/gnome

| XFCE
| GPL, LGPL, BSD
| x11-wm/xfce4

| MATE
| GPL 2.0, LGPL 2.0
| x11/mate

| Cinnamon
| GPL 2.0 or later
| x11/cinnamon

| LXQT
| GPL, LGPL
| x11-wm/lxqt

|===

[[kde-environment]]
=== KDE Plasma

KDE Plasma is an easy-to-use desktop environment. This desktop provides a suite of applications with a consistent look and feel, a standardized menu and toolbars, keybindings, color-schemes, internationalization, and a centralized, dialog-driven desktop configuration. More information on KDE can be found at the link:https://kde.org/[KDE homepage]. For FreeBSD-specific information, consult the link:https://freebsd.kde.org/[FreeBSD homepage at KDE].

[[kde-meta-install]]
==== Install KDE Plasma meta package

To install the KDE Plasma meta package with KDE Frameworks, Plasma Desktop and Applications execute:

[source, shell]
....
# pkg install kde5
....

[[kde-minimal-install]]
==== Minimal KDE Plasma installation

To install a minimal KDE Plasma execute:

[source, shell]
....
# pkg install plasma5-plasma
....

[TIP]
====
This installation is *really* minimal. Konsole must be installed separately executing:

[source, shell]
....
# pkg install konsole
....
====

[[kde-configuration]]
==== Configure KDE Plasma

KDE Plasma uses man:dbus-daemon[1] for a message bus and hardware abstraction. This application is automatically installed as a dependency of KDE Plasma.

Enable D-BUS service in `/etc/rc.conf` to start at system boot:

[source, shell]
....
# sysrc dbus_enable="YES"
....

To increase messages size execute:

[source, shell]
....
sysctl net.local.stream.recvspace=65536
sysctl net.local.stream.sendspace=65536
....

[[kde-start]]
==== Start KDE Plasma

The preferred KDE Plasma display manager is package:x11/sddm[]. To install package:x11/sddm[], execute:

[source, shell]
....
# pkg install sddm
....

Enable SDDM service in `/etc/rc.conf` to start at system boot:

[source, shell]
....
# sysrc sddm_enable="YES"
....

The keyboard language can be set in SDDM by running the following command (for Spanish, for example):

[source, shell]
....
# sysrc sddm_lang="es_ES"
....

A second method to start KDE Plasma is by manually invoking man:startx[1]. For this to work, the following line is needed in ~/.xinitrc:

[source, shell]
....
% echo "exec ck-launch-session startplasma-x11" > ~/.xinitrc
....

[[gnome-environment]]
=== GNOME

GNOME is a user-friendly desktop environment. It includes a panel for starting applications and displaying status, a desktop, a set of tools and applications, and a set of conventions that make it easy for applications to cooperate and be consistent with each other.

[[gnome-meta-install]]
==== Install GNOME meta pacakge

To install the GNOME meta package with GNOME Desktop and Applications, execute:

[source, shell]
....
# pkg install gnome
....

[[gnome-minimal-install]]
==== Minimal GNOME installation

To install the GNOME-lite meta package with a GNOME desktop slimmed down for only the basics, execute:

[source, shell]
....
# pkg install gnome-lite
....

[[gnome-configuration]]
==== Configure GNOME

GNOME requires `/proc` to be mounted. Add this line to `/etc/fstab` to mount this file system automatically during system startup:

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

GNOME uses man:dbus-daemon[1] for a message bus and hardware abstraction. This application is automatically installed as a dependency of GNOME.

Enable D-BUS service in `/etc/rc.conf` to start at system boot:

[source, shell]
....
# sysrc dbus_enable="YES"
....

It is often desirable to also start all GNOME services.

Enable GNOME services in `/etc/rc.conf` to start at system boot:

[source, shell]
....
# sysrc gnome_enable="YES"
....

[[gnome-start]]
==== Start GNOME

GNOME Display Manager is the preferred display manager for GNOME. GDM is installed as part of the GNOME package.

Enable GDM in `/etc/rc.conf` to start at system boot:

[source, shell]
....
# sysrc gdm_enable="YES"
....

A second method to start GNOME is by manually invoking man:startx[1]. For this to work, the following line is needed in `~/.xinitrc`:

[source, shell]
....
% echo "exec gnome-session" > ~/.xinitrc
....

[[xfce-environment]]
=== XFCE

XFCE is a desktop environment based on the GTK+, lightweight and provides a simple, efficient, easy-to-use desktop. It is fully configurable, has a main panel with menus, applets, and application launchers, provides a file manager and sound manager, and is themeable. Since it is fast, light, and efficient, it is ideal for older or slower machines with memory limitations.

[[xfce-install]]
==== Install XFCE

To install the XFCE meta package, execute:

[source, shell]
....
# pkg install xfce
....

[[xfce-configuration]]
==== Configure XFCE

XFCE requires `/proc` to be mounted. Add this line to `/etc/fstab` to mount this file system automatically during system startup:

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

XFCE uses man:dbus-daemon[1] for a message bus and hardware abstraction. This application is automatically installed as a dependency of XFCE.

Enable D-BUS in `/etc/rc.conf` to start at system boot:

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[xfce-start]]
==== Start XFCE

package:x11/lightdm[] is a display manager that supports different display technologies and is a good choice as it is very lightweight, requires little memory usage, and has fast performance.

To install it, execute:

[source, shell]
....
# pkg install lightdm lightdm-gtk-greeter
....

Enable lightdm in `/etc/rc.conf` to start at system boot:

[source, shell]
....
# sysrc lightdm_enable="YES"
....

A second method to start XFCE is by manually invoking man:startx[1]. For this to work, the following line is needed in `~/.xinitrc`:

[source, shell]
....
% echo '. /usr/local/etc/xdg/xfce4/xinitrc' > ~/.xinitrc
....

[[mate-environment]]
=== MATE

The MATE Desktop Environment is the continuation of GNOME 2.
// What does "traditional metaphors" mean?
It provides an intuitive and attractive desktop environment using traditional metaphors.

[[mate-meta-install]]
==== Install MATE meta package

To install the MATE meta package that includes the MATE Desktop with some extra applications such as text editor, archiver manager, etc., execute:

[source, shell]
....
# pkg install mate
....

[[mate-minimal-install]]
==== Minimal MATE installation

To install the MATE lite meta package with MATE desktop slimmed down for only the basics, execute:

[source, shell]
....
# pkg install mate-base
....

[[mate-configuration]]
==== Configure MATE

MATE requires `/proc` to be mounted. Add this line to `/etc/fstab` to mount this file system automatically during system startup:

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

MATE uses man:dbus-daemon[1] for a message bus and hardware abstraction. This application is automatically installed as a dependency of MATE. Enable D-BUS in `/etc/rc.conf` to start at system boot:

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[mate-start]]
==== Start MATE

package:x11/lightdm[] is a display manager that supports different display technologies and is a good choice as it is very lightweight, requires little memory usage, and has fast performance.

To install it, execute:

[source, shell]
....
# pkg install lightdm lightdm-gtk-greeter
....

Enable lightdm in `/etc/rc.conf` to start at system boot:

[source, shell]
....
# sysrc lightdm_enable="YES"
....

A second method to start MATE is by manually invoking man:startx[1]. For this to work, the following line is needed in `~/.xinitrc`:

[source, shell]
....
% echo "exec ck-launch-session mate-session" > ~/.xinitrc
....

[[cinnamon-environment]]
=== Cinnamon

Cinnamon is a UNIX(R) desktop which provides advanced innovative features and a traditional user experience. The desktop layout is similar to Gnome 2. The underlying technology is forked from Gnome Shell. The emphasis is put on making users feel at home and providing them with an easy to use and comfortable desktop experience.

[[cinnamon-install]]
=== Install Cinnamon

To install the Cinnamon package, execute:

[source, shell]
....
# pkg install cinnamon
....

[[cinnamon-configuration]]
==== Configure Cinnamon

Cinnamon requires `/proc` to be mounted. Add this line to `/etc/fstab` to mount this file system automatically during system startup:

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

Cinnamon uses man:dbus-daemon[1] for a message bus and hardware abstraction. This application is automatically installed as a dependency of Cinnamon. Enable D-BUS in `/etc/rc.conf` to start at system boot:

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[cinnamon-start]]
==== Start Cinnamon

package:x11/lightdm[] is a display manager that supports different display technologies and is a good choice as it is very lightweight, requires little memory usage, and has fast performance.

To install it execute:

[source, shell]
....
# pkg install lightdm lightdm-gtk-greeter
....

Enable lightdm in `/etc/rc.conf` to start at system boot:

[source, shell]
....
# sysrc lightdm_enable="YES"
....

A second method to start Cinnamon is by manually invoking man:startx[1]. For this to work, the following line is needed in `~/.xinitrc`:

[source, shell]
....
% echo "exec ck-launch-session cinnamon-session" > ~/.xinitrc
....

[[lxqt-environment]]
=== LXQT

LXQt is an advanced, easy-to-use, and fast desktop environment based on Qt technologies. It has been tailored for users who value simplicity, speed, and an intuitive interface. Unlike most desktop environments, LXQt also works fine with less powerful machines.

[[lxqt-install]]
==== Install LXQT

To install the LXQT meta package, execute:

[source, shell]
....
# pkg install lxqt
....

[[lxqt-configuration]]
==== Configure LXQT

LXQT requires `/proc` to be mounted. Add this line to `/etc/fstab` to mount this file system automatically during system startup:

[.programlisting]
....
# Device                Mountpoint      FStype  Options         Dump    Pass#
proc                    /proc           procfs  rw              0       0
....

LXQT uses man:dbus-daemon[1] for a message bus and hardware abstraction. This application is automatically installed as a dependency of LXQT.

Enable D-BUS in `/etc/rc.conf` to start at system boot:

[source, shell]
....
# sysrc dbus_enable="YES"
....

[[lxqt-start]]
==== Start LXQT

The preferred LXQT display manager is package:x11/sddm[]. To install package:x11/sddm[], execute:

[source, shell]
....
# pkg install sddm
....

Enable SDDM service in `/etc/rc.conf` to start at system boot:

[source, shell]
....
# sysrc sddm_enable="YES"
....

The keyboard language can be set in SDDM by running the following command (for example, for Spanish):

[source, shell]
....
# sysrc sddm_lang="es_ES"
....

A second method to start LXQT is by manually invoking man:startx[1]. For this to work, the following line is needed in `~/.xinitrc`:

[source, shell]
....
% echo "exec ck-launch-session startlxqt" > ~/.xinitrc
....

[[desktop-browsers]]
== 브라우저

This section describes how to install and configure some popular web browsers on a FreeBSD system, from full web browsers with high resource consumption to command line web browsers with reduced resource usage.

.Supported browsers
[options="header", cols="1,1,1,1"]
|===
| Name | License | Package | Resources Needed

| Firefox
| MPL 2.0
| package:www/firefox[]
| Heavy

| Chromium
| BSD-3 and others
| package:www/chromium[]
| Heavy

| Iridium browser
| BSD-3 and others
| package:www/iridium[]
| Heavy

| Falkon
| MPL 2.0
| package:www/falkon[]
| Heavy

| Konqueror
| GPL 2.0 or later
| package:x11-fm/konqueror[]
| Medium

| Gnome Web (Epiphany)
| GPL 3.0 or later
| package:www/epiphany[]
| Medium

| qutebrowser
| GPL 3.0 or later
| package:www/qutebrowser[]
| Medium

| Dillo
| GPL 3.0 or later
| package:www/dillo2[]
| Light

| Links
| GPL 2.0 or later
| package:www/links[]
| Light

| w3m
| MIT
| package:www/w3m[]
| Light

|===

[[firefox]]
=== Firefox

Firefox는 표준 준수 HTML 디스플레이 엔진, 탭 브라우징, 팝업 차단, 확장 기능, 향상된 보안 등의 기능을 갖춘 오픈 소스 브라우저입니다. Firefox는 Mozilla 코드베이스를 기반으로 합니다.

To install the package of the latest release version of Firefox, execute:

[source, shell]
....
# pkg install firefox
....

To instead install Firefox Extended Support Release (ESR) version, execute:

[source, shell]
....
# pkg install firefox-esr
....

[[chromium]]
=== Chromium

크로미움(Chromium)은 더 안전하고 빠르며 안정적인 웹 브라우징 환경을 구축하는 것을 목표로 하는 오픈소스 브라우저 프로젝트입니다. 크로미움은 탭 브라우징, 팝업 차단, 확장 기능 등을 제공합니다. 크로미움은 구글 크롬 웹 브라우저의 기반이 되는 오픈소스 프로젝트입니다.

To install Chromium, execute:

[source, shell]
....
# pkg install chromium
....

[NOTE]
====
Chromium의 실행 파일은 [.filename]#/usr/local/bin/chrome#이 아니라 [.filename]#/usr/local/bin/chromium#입니다.
====

[[iridium]]
=== Iridium browser

Iridium is a free, open, and libre browser modification of the Chromium code base, with privacy being enhanced in several key areas. Automatic transmission of partial queries, keywords, metrics to central services is inhibited and only occurs with consent.

To install Iridium, execute:

[source, shell]
....
# pkg install iridium
....

[[falkon]]
=== Falkon

Falkon is a new-ish and very fast QtWebEngine browser. It aims to be a lightweight web browser available on all major platforms. Falkon has all standard functions you expect from a web browser. It includes bookmarks, history (both also in sidebar) and tabs. Beyond that, you block ads with a builtin AdBlock plugin, block Flash content with Click2Flash and edit the local CA Certificates database with an SSL Manager.

To install Falkon, execute:

[source, shell]
....
# pkg install falkon
....

[[konqueror]]
=== Konqueror

Konqueror is more than a web browser as it is also a file manager and a multimedia viewer. It supports WebKit, a rendering engine used by many modern browsers including Chromium, as well as its own KHTML engine.

To install Konqueror, execute:

[source, shell]
....
# pkg install konqueror
....

[[gnome-web-epiphany]]
=== Gnome Web (Epiphany)

Gnome Web (Epiphany) is a web browser designed to be as lightweight and fast as possible, at the expense of many of the features found in other browsers.

To install Gnome Web (Epiphany), execute:

[source, shell]
....
# pkg install epiphany
....

[[qutebrowser]]
=== qutebrowser

Qutebrowser is a keyboard-focused browser with a minimal GUI. It is based on Python and PyQt5 and free software, licensed under the GPL.
// What are these and how does this information help in this context?
It was inspired by other browsers/addons like dwb and Vimperator/Pentadactyl.

To install qutebrowser, execute:

[source, shell]
....
# pkg install qutebrowser
....

[[dillo]]
=== Dillo

Dillo aims to be a multiplatform alternative browser that is small, stable, developer-friendly, usable, fast, and extensible. This new, experimental version of Dillo is based upon FLTK toolkit, rather than GTK1, and has been substantially rewritten.

To install Dillo, execute:

[source, shell]
....
# pkg install dillo2
....

[[links]]
=== Links

A lynx-like WWW browser with text and graphics modes with many features like displaying tables, menus, etc.

To install Links, execute:

[source, shell]
....
# pkg install links
....

[[w3m]]
=== w3m

w3m is a pager/text-based web browser. It is a similar application to Lynx, but it has several features Lynx doesn't have like rendering tables and rendering frames.

To install w3m, execute:

[source, shell]
....
# pkg install w3m
....

[[desktop-development]]
== Development tools

This section describes how to install and configure some popular development tools on a FreeBSD system.

.Supported development tools
[options="header", cols="1,1,1,1"]
|===
| Name | License | Package | Resources Needed

| Visual Studio Code
| MIT
| package:editors/vscode[]
| Heavy

| Qt Creator
| QtGPL
| package:devel/qtcreator[]
| Heavy

| Kdevelop
| GPL 2.0 or later and LGPL 2.0 or later
| package:devel/kdevelop[]
| Heavy

| Eclipse IDE
| EPL
| package:java/eclipse[]
| Heavy

| Vim
| VIM
| package:editors/vim[]
| Light

| Neovim
| Apache 2.0
| package:editors/neovim[]
| Light

| GNU Emacs
| GPL 3.0 or later
| package:editors/emacs[]
| Light

|===

[[vs-code]]
=== Visual Studio Code

Visual Studio Code is a type of tool that combines the simplicity of a code editor with what developers need for their core edit-build-debug cycle. It provides comprehensive editing and debugging support, an extensibility model, and lightweight integration with existing tools.

To install Visual Studio Code, execute:

[source, shell]
....
# pkg install vscode
....

[[qt-creator]]
=== Qt Creator

Qt Creator is a cross-platform IDE (integrated development environment) tailored to the needs of Qt developers. Functionalities included with Qt Creator are:

* code editor with C++, QML and ECMAscript support;
* rapid code navigation tools;
* static code checking and style hints as you type;
* context sensitive help;
* visual debugger;
* integrated GUI layout and forms designer.

To install Qt Creator, execute:

[source, shell]
....
# pkg install qtcreator
....

[[kdevelop]]
=== kdevelop

Open source, feature-full, plugin extensible IDE for C/C++ and other programming languages. It is based on KDevPlatform and the KDE and Qt libraries, and it has been under development since 1998.

To install kdevelop, execute:

[source, shell]
....
# pkg install kdevelop
....

[[eclipse]]
=== Eclipse IDE

The Eclipse Platform is an open extensible IDE for anything and yet nothing in particular. The Eclipse Platform provides building blocks and a foundation for constructing and running integrated software-development tools. The Eclipse Platform allows tool builders to independently develop tools that integrate with other people's tools.

To install Eclipse IDE, execute:

[source, shell]
....
# pkg install eclipse
....

[[vim]]
=== Vim

Vim is a highly configurable text editor built to enable efficient text editing. It is an improved version of the vi editor distributed with most UNIX systems.

Vim is often called a "programmer's editor," and so useful for programming that many consider it an entire IDE. It's not just for programmers, though. Vim is perfect for all kinds of text editing, from composing email to editing configuration files.

To install Vim, execute:

[source, shell]
....
# pkg install vim
....

[[neovim]]
=== Neovim

Neovim is an aggressive refactor of package:editors/vim[]. It represents a complete overhaul of the codebase with many sanity improvements, including sensible defaults, a built-in terminal emulator, asynchronous plugin architecture, and powerful APIs designed for speed and extensibility. It retains full compatibility with almost all Vim plugins and scripts.

To install Neovim, execute:

[source, shell]
....
# pkg install neovim
....

[[gnu-emacs]]
=== GNU Emacs

GNU Emacs is an extensible, customizable, free/libre text editor. At its core is an interpreter for Emacs Lisp, a dialect of the Lisp programming language with extensions to support text editing.

To install GNU Emacs, execute:

[source, shell]
....
# pkg install emacs
....

[[desktop-productivity]]
== Desktop office productivity

When it comes to productivity, users often look for an office suite or an easy-to-use word processor. While some desktop environments like <<kde-environment, KDE Plasma>> provide an office suite, there is no default productivity package. Several office suites and graphical word processors are available for FreeBSD, regardless of the installed desktop environments.

이 섹션에서는 다음과 같은 인기 있는 생산성 소프트웨어를 설치하는 방법을 설명하고 해당 애플리케이션이 리소스를 많이 사용하거나, 포트에서 컴파일하는 데 시간이 걸리거나, 주요 종속성이 있는지를 알려줍니다.

.Supported Desktop office productivity suites
[options="header", cols="1,1,1,1"]
|===
| Name | License | Package | Resources Needed

| LibreOffice
| MPL 2.0
| package:editors/libreoffice[]
| Heavy

| Calligra Suite
| LGPL and GPL
| package:editors/calligra[]
| Medium

| AbiWord
| GPL 2.0 or later
| package:editors/abiword[]
| Medium

|===

[[libreoffice]]
=== LibreOffice

LibreOffice is a free software office suite developed by http://www.documentfoundation.org/[The Document Foundation]. It is compatible with other major office suites and available on a variety of platforms. It is a rebranded fork of Apache OpenOffice and includes applications found in a complete office productivity suite: a word processor, spreadsheet, presentation manager, drawing program, database management program, and a tool for creating and editing mathematical formulæ. It is available in a number of different languages and internationalization has been extended to interfaces, spell checkers, and dictionaries. More information about LibreOffice can be found at http://www.libreoffice.org/[libreoffice.org].

To install LibreOffice, execute:

[source, shell]
....
# pkg install libreoffice
....

The LibreOffice package comes by default only in English. To have a localized version of LibreOffice it is necessary to install a language pack. For example, for the version localized in Spanish, it is necessary to install the package package:editors/libreoffice-es[] with the command:

[source, shell]
....
# pkg install libreoffice-es
....

[[calligra]]
=== Calligra

The KDE Plasma desktop environment includes an office suite which can be installed separately from KDE Plasma. Calligra includes standard components that can be found in other office suites. Words is the word processor, Sheets is the spreadsheet program, Stage manages slide presentations, and Karbon is used to draw graphical documents.

To install Calligra, execute:

[source, shell]
....
# pkg install calligra
....

[[abiword]]
=== AbiWord

AbiWord는 Microsoft(R) Word와 모양과 느낌이 비슷한 무료 워드 프로세싱 프로그램입니다. 빠르고 다양한 기능이 포함되어 있으며 사용자 친화적입니다.

AbiWord는 Microsoft(R) [.filename]#.rtf#와 같은 일부 독점 형식을 포함하여 다양한 파일 형식을 가져오거나 내보낼 수 있습니다.

To install AbiWord, execute:

[source, shell]
....
# pkg install abiword
....

[[desktop-viewers]]
== 도큐먼트 뷰어

UNIX(R)의 등장 이후 일부 새로운 문서 형식이 인기를 얻고 있으며, 이러한 형식에 필요한 뷰어가 기본 시스템에서 제공되지 않을 수 있습니다. 이 섹션에서는 다음 문서 뷰어를 설치하는 방법을 설명합니다:

.Supported Document Viewers
[options="header", cols="1,1,1,1"]
|===
| Name | License | Package | Resources Needed

| Okular
| GPL 2.0
| package:graphics/okular[]
| Heavy

| Evince
| GPL 2.0
| package:graphics/evince[]
| Medium

| ePDFView
| GPL 2.0
| package:graphics/epdfview[]
| Medium

| Xpdf
| GPL 2.0
| package:graphics/xpdf[]
| light

|===

[[okular]]
=== Okular

Okular is a universal document viewer, part of the KDE Plasma project.

Okular combines excellent functionality with the versatility of supporting different kind of documents, like PDF, Postscript, DjVu, CHM, XPS, ePub and others.

To install Okular, execute:

[source, shell]
....
# pkg install okular
....

[[evince]]
=== Evince

Evince is a document viewer for multiple document formats including PDF and Postscript. Part of the GNOME project. The goal of evince is to replace document viewers such as ggv and gpdf with a single, simple application.

To install Evince, execute:

[source, shell]
....
# pkg install evince
....

[[epdfview]]
=== ePDFView

ePDFView is a lightweight PDF document viewer that only uses the Gtk+ and Poppler libraries. The aim of ePDFView is to make a simple PDF document viewer, similar to Evince but without using the GNOME libraries.

To install ePDFView, execute:

[source, shell]
....
# pkg install epdfview
....

[[xpdf]]
=== Xpdf

작은 FreeBSD PDF 뷰어를 선호하는 사용자를 위해, Xpdf는 리소스를 거의 필요로 하지 않는 가볍고 효율적인 뷰어를 제공합니다. 표준 X 글꼴을 사용하며 추가 툴킷이 필요하지 않습니다.

To install Xpdf, execute:

[source, shell]
....
# pkg install xpdf
....

[[desktop-finance]]
== 금융

FreeBSD 데스크탑에서 개인 재정을 관리하기 위해 강력하고 사용하기 쉬운 몇 가지 애플리케이션을 설치할 수 있습니다. 일부는 Quicken 및 Excel에서 사용하는 형식과 같이 널리 사용되는 파일 형식과 호환됩니다.

이 섹션에서는 이러한 프로그램을 다룹니다:

.Supported Finance programs
[options="header", cols="1,1,1,1"]
|===
| Name | License | Package | Resources Needed

| KMyMoney
| GPL 2.0
| package:finance/kmymoney[]
| Heavy

| GnuCash
| GPL 2.0 and GPL 3.0
| package:finance/gnucash[]
| Heavy

|===

[[kmymoney]]
=== KMyMoney

KMyMoney는 KDE 커뮤니티에서 만든 개인 금융 애플리케이션입니다. KMyMoney는 상용 개인 재무 관리자 애플리케이션에서 볼 수 있는 중요한 기능을 제공하는 것을 목표로 합니다. 또한 사용 편의성과 적절한 이중 입력 회계 기능을 강조합니다. KMyMoney는 표준 Quicken QIF 파일에서 가져오고, 투자를 추적하고, 여러 통화를 처리하며, 다양한 보고서를 제공합니다.

To install KMyMoney, execute:

[source, shell]
....
# pkg install kmymoney
....

[[gnucash]]
=== GnuCash

GnuCash는 사용자 친화적이면서도 강력한 애플리케이션을 최종 사용자에게 제공하기 위한 GNOME의 노력의 일환입니다. GnuCash는 수입과 지출, 은행 계좌, 주식을 추적하는 데 사용할 수 있습니다. 전문성을 유지하면서도 직관적인 인터페이스가 특징입니다.

GnuCash는 스마트 레지스터, 계층적 계정 시스템, 다양한 키보드 가속기 및 자동 완성 방법을 제공합니다. 단일 트랜잭션을 여러 개의 세부 트랜잭션으로 분할할 수 있습니다. GnuCash는 Quicken QIF 파일을 가져오고 병합할 수 있습니다. 또한 대부분의 국제 날짜 및 통화 형식을 처리합니다.

To install GnuCash, execute:

[source, shell]
....
# pkg install gnucash
....
